[package]
name = "mini-raft"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9"
tokio = { version = "1", features = ["full"] }
tonic = "0.14"
tonic-prost = "0.14"
prost = "0.14"

[build-dependencies]
tonic-prost-build = "0.14"